const strings = {
  no_connection: 'Umm...parece que você está sem internet!',
  reload: 'Clique aqui para recarregar :)',
  no_games: 'Você ainda não adicionou nenhum game que você zerou :(',
  adicione_ja: 'Adicione seu jogo, bora! 😁👌',
  lets_save_game: 'Uhuu! Bora salvar o jogo',
  cover_label: 'Capa',
  game_name_label: 'Nome do jogo',
  game_desc_label: 'Descrição do jogo (opcional)',
  plataform_label: 'Plataforma/Console',
  finished_date_label: 'Quando você zerou o game?',
  cover_placeholder: 'Link da imagem do jogo',
  game_name_placeholder: 'Digite o nome do jogo',
  game_desc_placeholder: 'Descreva como foi zerar o game',
  plataform_placeholder: 'Steam',
  finished_date_placeholder: 'Digite quando você zerou o game',
  selecione: 'Selecione',
  all_your_games_here: 'Todos os seus games aqui',
  show_your_achieves: 'Mostre suas Conquistas ',
  enter_now: 'Entre agora',
  its_free_and_easy: 'É grátis e fácil',
  start: 'Iniciar cadastro',
  change_photo: 'Trocar foto',
  username_label: 'Username',
  destroy_ads: 'Eliminar anúncios',
  delete: 'Deletar',
  edit: 'Editar',
  finished_at: 'Finalizado em:',
  sair: 'Sair',
  email: 'Email',
  password: 'Senha',
  enter: 'Entrar',
  sign_up: 'Cadastrar',
  recovery_password: 'Recuperar senha',
  fill_all: 'Preencha todos os campos :(',
  err_invalid_email: 'Este email é inválido :(',
  err_invalid_password: 'A senha está incorreta :(',
  url_on: 'https://game-state-backend-4ww3.vercel.app/',
  url_localhost: 'http://192.168.100.31:80',
  //url_localhost: 'http://192.168.43.144:80',
  save_edit: 'Salvar edição',
  edit_cover: 'Editar capa',
  game_updated: 'Jogo atualizado com sucesso :)',
};

export {strings};
